### ISSUE TITLE
models.tssd_net not found

### ISSUE THREAD

**Issue by sakira** [AGenCyLab/SPCUP2022#4]
from models.tssd_net.models import SSDNet1D as ResTSSDNet
ModuleNotFoundError: No module named 'models.tssd_net'

**Comment by mahieyin-rahmun** [comment]
Ma'am, did you use the `--recursive` flag while cloning?

**Comment by mahieyin-rahmun** [comment]
I have fixed the issue and have tested it by using `git clone https://github.com/AGenCyLab/SPCUP2022.git --recursive` to clone the repository. It now pulls the submodule and places it in the correct path. Could you kindly check if this also works at your end?

**Comment by sakira** [comment]
> 

Thanks. For local branch the following command would be useful:
> git submodule init
> git submodule update
