### ISSUE TITLE
SPCUP2022.utils.config not found 

### ISSUE THREAD

**Issue by rafathasan** [AGenCyLab/SPCUP2022#6]
I get this import error when try to run train_tssdnet.py from SPCUP2022. And I have used --recursive while cloning. Error raise from train_tssdnet.py line 6. Changing from "from SPCUP2022.utils.config import load_config_file" to "from utils.config import load_config_file" fix the issue.

**Comment by mahieyin-rahmun** [comment]
Hi, thanks for bringing this up. Apparently VS Code `auto-import` breaks absolute imports. Can you check and report back if it's fixed now?

**Comment by rafathasan** [comment]
It has been fixed. thanks!
